version: 1.0.0.{build}
os: Visual Studio 2015
branches:
  only:
  - master
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
before_build:
  - nuget restore
build:
  project: Swift.sln
after_test:
- ps: .\Deployment\Create-Release.ps1
artifacts:
- path: '**\Setup.exe'
  name: Setup.exe
- path: '**\Swift.*.nupkg'
deploy:
- provider: GitHub
  name: releases
  on:
    branch: master
    appveyor_repo_tag: true