version: 1.0.0.{build}
os: Visual Studio 2015
branches:
  only:
  - master
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
before_build:
  - nuget restore
build:
  project: Swift.sln
after_test:
- ps: .\Deployment\Create-Release.ps1
artifacts:
- path: '**\Swift.dll'
  name: Swift.dll
- path: '.\Swift.*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: 3VAcdRzB2F5zv0BsV4Z+o31z5ZuiBWxmvz48/bIcV7/Zg74BiCMpqy9Iwdlm7BhS
  artifact: /.*\.nupkg/
